import PDFDocument from 'pdfkit';

interface PurchaseOrderData {
  poNumber: string;
  orderNumber: string;
  retailerInfo: {
    businessName: string;
    contactPerson: string;
    phoneNumber: string;
    address: {
      street: string;
      city: string;
      state: string;
      pincode: string;
      country: string;
    };
  };
  items: Array<{
    itemCode: string;
    itemName: string;
    color: string;
    fabric: string;
    pricePerPc: number;
    pricePerSet: number;
    quantityPcs: number;
    quantitySets: number;
    totalPcs: number;
    totalAmount: number;
  }>;
  poSummary: {
    totalPcs: number;
    totalSets: number;
    totalAmountBeforeGST: number;
    gstRate: number;
    gstAmount: number;
    totalAmountAfterGST: number;
  };
  terms: {
    paymentTerms: string;
    deliveryTerms: string;
    warranty: string;
  };
  generatedBy: string;
  generatedAt: Date;

}

export function generatePurchaseOrderPDF(data: PurchaseOrderData): Buffer {
  const doc = new PDFDocument({ margin: 50 });
  const chunks: Buffer[] = [];

  doc.on('data', (chunk) => chunks.push(chunk));

  // Header
  doc.fontSize(24).font('Helvetica-Bold').text('PURCHASE ORDER', { align: 'center' });
  doc.moveDown();
  
  // Company Info
  doc.fontSize(16).font('Helvetica-Bold').text('Ethnics by Aravalli');
  doc.fontSize(10).font('Helvetica').text('Manufacturer of Ethnic Wear');
  doc.text('Jaipur, Rajasthan, India');
  doc.text('Phone: +91 9828422208');
  doc.text('Email: info@ethnicsbyaravalli.com');
  doc.moveDown();

  // PO Details
  doc.fontSize(12).font('Helvetica-Bold').text('Purchase Order Details');
  doc.fontSize(10).font('Helvetica');
  doc.text(`PO Number: ${data.poNumber}`);
  doc.text(`Order Number: ${data.orderNumber}`);
  doc.text(`Date: ${data.generatedAt.toLocaleDateString()}`);
  doc.text(`Generated By: ${data.generatedBy}`);
  doc.moveDown();

  // Retailer Info
  doc.fontSize(12).font('Helvetica-Bold').text('Retailer Information');
  doc.fontSize(10).font('Helvetica');
  doc.text(`Business Name: ${data.retailerInfo.businessName}`);
  doc.text(`Contact Person: ${data.retailerInfo.contactPerson}`);
  doc.text(`Phone: ${data.retailerInfo.phoneNumber}`);
  doc.text(`Address: ${data.retailerInfo.address.street}`);
  doc.text(`         ${data.retailerInfo.address.city}, ${data.retailerInfo.address.state} - ${data.retailerInfo.address.pincode}`);
  doc.text(`         ${data.retailerInfo.address.country}`);
  doc.moveDown();

  // Items Table
  doc.fontSize(12).font('Helvetica-Bold').text('Order Items');
  doc.moveDown();

  // Table Header
  const tableTop = doc.y;
  const tableLeft = 50;
  const colWidths = [60, 120, 60, 60, 60, 60, 60];
  const headers = ['Code', 'Item Name', 'Color', 'Fabric', 'Sets', 'Pcs', 'Amount'];

  doc.fontSize(8).font('Helvetica-Bold');
  headers.forEach((header, i) => {
    doc.text(header, tableLeft + colWidths.slice(0, i).reduce((a, b) => a + b, 0), tableTop);
  });

  // Table Content
  let currentY = tableTop + 20;
  doc.fontSize(8).font('Helvetica');

  data.items.forEach((item) => {
    if (currentY > 700) {
      doc.addPage();
      currentY = 50;
    }

    const rowData = [
      item.itemCode,
      item.itemName,
      item.color,
      item.fabric,
      item.quantitySets.toString(),
      item.totalPcs.toString(),
      `₹${item.totalAmount.toLocaleString()}`
    ];

    rowData.forEach((text, i) => {
      doc.text(text, tableLeft + colWidths.slice(0, i).reduce((a, b) => a + b, 0), currentY);
    });

    currentY += 15;
  });

  doc.moveDown(2);

  // Summary
  doc.fontSize(12).font('Helvetica-Bold').text('Order Summary');
  doc.fontSize(10).font('Helvetica');
  doc.text(`Total Sets: ${data.poSummary.totalSets}`);
  doc.text(`Total Pieces: ${data.poSummary.totalPcs}`);
  
  doc.fontSize(12).font('Helvetica-Bold').text(`Total Amount: ₹${data.poSummary.totalAmountAfterGST.toLocaleString()}`);
  doc.moveDown();

  // Terms and Conditions
  doc.fontSize(12).font('Helvetica-Bold').text('Terms & Conditions');
  doc.fontSize(10).font('Helvetica');
  doc.text(`Payment Terms: ${data.terms.paymentTerms}`);
  doc.text(`Delivery Terms: ${data.terms.deliveryTerms}`);
  doc.text(`Warranty: ${data.terms.warranty}`);
  doc.moveDown();

  // Footer
  doc.fontSize(10).font('Helvetica').text('Thank you for your business!', { align: 'center' });
  doc.text('Ethnics by Aravalli - Premium Ethnic Wear Manufacturer', { align: 'center' });

  doc.end();

  return Buffer.concat(chunks);
} 